### ISSUE TITLE
Unify thread synchronization APIs with libtuv

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#107]
Since `libtuv` is integrated into `dcurl`, we can unify the use of thread synchronization with [libtuv APIs](https://github.com/pando-project/libtuv/wiki/libtuv-APIs). Specifically, all occurrence of mutex and semaphore can be replaced with the corresponding libtuv equivalents, which are implemented with cross-platform support in mind. It implies that we can concentrate on abstract computing and resource management without enumerating GNU/Linux, macOS, and even MS-Windows ports.

**Comment by jserv** [comment]
Related: #102

**Comment by marktwtn** [comment]
Although replacing thread synchronization APIs with `libtuv` is trivial, it would have issue when compiling `dcurl` on other platform.
For example, the  `de10 nano` hardware platform.
Check #105 for reference.

The `libtuv` needs to specify the supported hardware and OS, but the current detection method in `mk/submodule.mk` is quite simple.
