### ISSUE TITLE
Introduce batched binary-encoded ternary Curl

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#123]
Luca Moser introduced [bct_curl](https://github.com/luca-moser/bct_curl), which implements a batched binary encoded ternary Curl. The batched BCTCurl collects up to a timeout of 50 milliseconds trits inputs to hash. All the inputs must be of the same length. On an i7-8850u CPU, it is able to throughput ~15k txs hashes/s (per core) given 8019 trits of transaction input data per request. Running on 4 cores, this yields over ~50k transaction hashes per second. A basic Curl implementation achieves only a throughput of about 320 txs hashes/s per core.

The corresponding [batched-hasher branch for IRI](https://github.com/luca-moser/iri/commits/batched-hasher) is pushed for integrating batched binary encoded ternary Curl. This work is effective to `dcurl` because we are about to have broker-assisted remote interface (#91) and revised threading model (#102) to coupled with batched requests.

**Comment by wusyong** [comment]
[curl-p in entangled](https://github.com/iotaledger/entangled/tree/develop/common/crypto/curl-p) also has this in it.

**Comment by marktwtn** [comment]
As illustrated in the readme.md of the [`Kerl`](https://github.com/iotaledger/kerl) repository, `Curl-P-81` is used in:

- Calculate the Proof-of-Work
- Generate the transaction hash

However, the source code of the former is far more complex than the latter.
[curl-p in entangled](https://github.com/iotaledger/entangled/tree/develop/common/crypto/curl-p) and [bct_curl](https://github.com/luca-moser/bct_curl) only focus on the application like generating the transaction hash.

Let us have a small conclusion:
1. To use the concept of batched `Curl` in calculating the PoW, it would take a lot of work.
    I do not even sure about the possibility of the implementation.

2. If it is implemented well, we do increase the number of transactions per PoW calculation but decrease the speed of finding the nonce value of each transaction.

    Take `dcurl` generic C implementation as an example:
The core function `transform64()` can do the hash 64 times in one call.
original version - 64 hash times / 1 transaction
batched version - 64 hash times / 64 transactions

**Comment by marktwtn** [comment]
The `transform()` function of `Curl` is the key function of hashing.
And the basic calculation unit is a **trit**.

The simplest `transform()` function stores a **trit** in `int8_t`.
Example: the [curl.c](https://github.com/DLTcollab/dcurl/blob/develop/src/curl.c) in `dcurl`

However, it is not efficient.
In `ccurl`, `dcurl` and [`bct_curl`](https://github.com/luca-moser/bct_curl), they use a skill to store a **trit** in a single bit.
The `trit` value is first changed to a **2-bit** value as shown in the table:

| Original value | High part | Low part |
| --- | ------------- | ------------- |
| -1 | 0 | 1 |
| 0 | 1 | 1 |
| 1 | 1 | 0 |

In `transform()` function, it handles the high part and low part together.
By using the skill with storing the **trits** in 64-bit data type:
- The time of finding the nonce value is decreased.
  (by hashing 64 different nonce value at the same time, like `ccurl` and `dcurl`)
- The hashing function can handle 64 transaction inputs at the same time.
  (like `bct_curl`)

---

The reason why we can not apply the batched technique of `bct_curl` directly to `dcurl`:
- Different purpose
  The [pull request](https://github.com/iotaledger/iri/pull/1372) of `bct_curl` and [curl-p in entangled](https://github.com/iotaledger/entangled/tree/develop/common/crypto/curl-p) do the batched things for generating the hash, not for the PoW.
  The PoW source code in `IRI` and `entangled` remains the same, one PoW for one transaction.
- Contradiction
  Even if we port the concept of batched transactions in our `dcurl` `transform()` function (with a lot of hard work),
  the behaviour would like hashing 64 different nonce value, where each nonce value is for each transaction.
  It contradicts to the original design of `dcurl`. We lost the chance to hash more different nonce value for a single transaction.
- Lack of multiple inputs
  Take `IRI` and `attachToTangle()` API as an example.
  The `attachToTangle` API is a `synchronized` Java function, which limits only one thread can execute the function at the same time.
  In `attachToTangle()`, it has a list of transactions waiting for doing the PoW.
  However, `attachToTangle()` API focuses on a transaction bundle, which means the list of transactions has dependency.
  The transaction can not be handled until the previous transaction finishes it PoW calculation.

**Comment by jserv** [comment]
Since @marktwtn enabled parallel `attachToTangle` operation with `IRI-1.8.0`, is there room for speeding up BatchedBCTCurl via dcurl fastpath?

**Comment by marktwtn** [comment]
> Since @marktwtn enabled parallel `attachToTangle` operation with `IRI-1.8.0`, is there room for speeding up BatchedBCTCurl via dcurl fastpath?

I do not think `attachToTangle` and `BatchedBCTCurl` are related.
One is for doing the PoW, and the other one is for generating the transaction hash or something else.
The source code of `attachToTangle` does not even use any batched related class.
