### ISSUE TITLE
Error building with gpu cuda 10.1

### ISSUE THREAD

**Issue by tylerw1369** [DLTcollab/dcurl#131]
Im getting this error. Im not sure if it is something i need to do on my computer but i dont believe it is.
![image](https://user-images.githubusercontent.com/39392335/55023391-4f0ccf00-4fc2-11e9-9624-d948cbe641e2.png)

**Comment by marktwtn** [comment]
@tylerw1369 , please try the command `$ sudo apt install ocl-icd-opencl-dev` to install the OpenCL header files and library.

**Comment by tylerw1369** [comment]
oh stupid me that was the problem. thanks
