### ISSUE TITLE
Remote interface: Implement local fallback PoW

### ISSUE THREAD

**Issue by ajblane** [DLTcollab/dcurl#139]
When defining and building the use of remote interface, if the build command is `make BUILD_REMOTE_INTERFACE=1`, after using the build command, the dcurl only supports remote interface and other PoW optimizations is disable. Therefore, in order to use local dcurl when running remote interface fails, we may require building the supported command at least is `make BUILD_REMOTE_INTERFACE=1` with `BUILD_AVX=1` or other PoW optimizations. To support the behavior of this command, we need to modify dcurl.c to support the local dcurl use when running remote interface fails. Or any suggestion?

**Comment by jserv** [comment]
When `BUILD_REMOTE` is triggered, both [stub and skeleton](https://en.wikipedia.org/wiki/Stub_(distributed_computing)) programs are about to be generated to facilitate RPC, which does not bother existing PoW implementations.
