### ISSUE TITLE
Remote interface: Integrate IRI

### ISSUE THREAD

**Issue by ajblane** [DLTcollab/dcurl#152]
Related to #133
Related to https://github.com/DLTcollab/general/issues/149
Related to https://github.com/DLTcollab/general/issues/147

**Comment by marktwtn** [comment]
The way we use remote interface is to dynamically link the **rabbitMQ** shared library.

In the **dcurl** executable files, it works well.
However, it has some problem with the **IRI** integration.
**IRI** uses **dcurl** with its shared library `libdcurl.so`, and it can not load the `librabbitmq.so` correctly.

I'll try to figure out another way to use remote interface without any problem.

**Comment by marktwtn** [comment]
I decide to use **rabbitMQ** position-independent object files instead of its shared library.
The **dcurl** executable files and shared library would be compiled with the extra **rabbitMQ** objects files, which increases the size.
However, it is much straightforward.
