### ISSUE TITLE
New updated build won't compile on de10 nano

### ISSUE THREAD

**Issue by tylerw1369** [DLTcollab/dcurl#169]
For some reason I have to build with much older dcurl version on my de10 nano. This is what it states. 
![Capture+_2019-07-11-21-49-39](https://user-images.githubusercontent.com/39392335/61103359-8181f100-a426-11e9-9e6a-248abb7e084f.png)

**Comment by marktwtn** [comment]
I will rewrite the `Makefile` to ensure that the **OpenSSL** would not be required when the `BUILD_REMOTE` option is not enabled.

**Comment by marktwtn** [comment]
@tylerw1369 please remember to add the build option `BOARD=de10nano` to avoid build fail after this issue is fixed.

Build option: https://github.com/DLTcollab/dcurl/blob/develop/docs/build-n-test.md

**Comment by tylerw1369** [comment]
Will do!  👍

**Comment by tylerw1369** [comment]
Did something change in the way dcurl works?  Is it still backwards compatible with ccurl?  When I used it in a ccurl pow node it errored out and won't process pow.

**Comment by jserv** [comment]
@tylerw1369, Regarding `ccurl` compatibility, can you create a new issue along with the procedure we can reproduce?
