### ISSUE TITLE
Log the debug messages of remote worker

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/dcurl#175]
To observe the behaviour of the remote worker, the debug messages should be logged.
However, they were not redirected to the logging file as expected.

The remote worker is running as an infinite loop and can be interrupted by sending a signal.
The debug messages buffered by the OS somehow disappeared with this working style after the interruption.
Flushing the buffer can solve the problem.

**Comment by jserv** [comment]
The logging facilities should be interchangeable. e.g. either to use logger functions defined in entangled or be standalone.
