### ISSUE TITLE
Javah not found error

### ISSUE THREAD

**Issue by tylerw1369** [DLTcollab/dcurl#194]
I'm getting a javah error not found when trying to build.  I am using Java 1.8.0.  Any suggestions?

tyler@tyler-MS-7B79:/testing/dcurl$ make BUILD_AVX=1 BUILD_GPU=1 BUILD_JNI=1
mk/java.mk:25: *** "javah is not available. Please check JDK installation".  Stop.
tyler@tyler-MS-7B79:/testing/dcurl$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**Comment by marktwtn** [comment]
Did you set the environment variable **JAVA_HOME** to your Java directory?

**Comment by tylerw1369** [comment]
Checked it and now it's saying this.  Kinda wierd. 

tyler@tyler-MS-7B79:/testing/dcurl$ make BUILD_AVX=1 BUILD_GPU=1 BUILD_JNI=1
make: *** No rule to make target '/usr/lib/jvm/java-8-oracle/include/jni.h', needed by 'build/jni/iri-pearldiver-exlib.o'.  Stop.
tyler@tyler-MS-7B79:/testing/dcurl$

**Comment by marktwtn** [comment]
You are using `OpenJDK` and the header file path is `java-8-oracle`?

What is the value of your environment variable **JAVA_HOME**?
And please list the directories under the `/usr/lib/jvm`.
