### ISSUE TITLE
Can't use libdcurl.so on my iota.keccak.pow.node software 

### ISSUE THREAD

**Issue by tylerw1369** [DLTcollab/dcurl#212]
Any thoughts?  This is my output error when I try pow.
er@arm:~/iota.keccak.pow.node.js$ sudo node main.js
12:58:51 - 2 Workers started
12:58:51 - Bound to 0.0.0.0 and listening on and port 19000
12:59:26 - Error performing PoW
{ success: false,
  error:
   'CCurl not reachable - Please fix this prior calling this function!' }
/home/tyler/iota.keccak.pow.node.js/main.js:39
                res.status(500);
                ^

ReferenceError: res is not defined
    at Worker.<anonymous> (/home/tyler/iota.keccak.pow.node.js/main.js:39:17)
    at Worker.emit (events.js:194:15)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Nothing has changed accept updating to the new dcurl build.

Edit:  I am renaming the libdcurl.so file to libccurl.so as is instructed.

**Comment by jserv** [comment]
The cCurl compatibility layer is kept. @tylerw1369, can you show the step to reproduce?

**Comment by tylerw1369** [comment]
I cloned dcurl and issued

tyler@arm:~$ make BOARD=de10nano BUILD_FPGA_ACCEL=1 BUILD_STAT=1

Then took the libdcurl.so file from the build directory and copied it to iota.keccak.pow.node.js folder as libdcurl.so
Start the pow node with sudo node main.js 
Then it gives me the error when I send pow to it

**Comment by marktwtn** [comment]
> I cloned dcurl and issued
> 
> tyler@arm:~$ make BOARD=de10nano BUILD_FPGA_ACCEL=1 BUILD_STAT=1

Please try the build command
```
$ make BOARD=de10nano BUILD_FPGA_ACCEL=1 BUILD_COMPAT=1
```

The `BUILD_COMPAT` option is for building the extra cCurl compatible interface.

**Comment by tylerw1369** [comment]
Ok that was the issue.  Thanks for some reason I thought the BUILD_COMPAT was removed.  Thanks for your help

**Comment by marktwtn** [comment]
> Ok that was the issue. Thanks for some reason I thought the BUILD_COMPAT was removed. Thanks for your help

We mark it as deprecated but it still exists.
You can always find the updated build option description here [Document - build instruction](https://github.com/DLTcollab/dcurl/blob/develop/docs/build-n-test.md#build-instructions).

**Comment by tylerw1369** [comment]
Awesome thanks again for all the work you guys have done!
