### ISSUE TITLE
Trouble with new build

### ISSUE THREAD

**Issue by tylerw1369** [DLTcollab/dcurl#224]
I'm trying to build the new version of dcurl and I am getting the following error after "make clean".  

tyler@arm:~/dcurl-update/dcurl$ make BOARD=de10nano BUILD_FPGA_ACCEL=1 BUILD_COMPAT=1
readlink: missing operand
Try 'readlink --help' for more information.
  CC    build/compat_ccurl.o
src/compat_ccurl.c: In function ‘ccurl_pow’:
src/compat_ccurl.c:23:9: error: too few arguments to function ‘dcurl_init’
         dcurl_init();
         ^~~~~~~~~~
In file included from src/compat_ccurl.c:11:0:
src/dcurl.h:51:6: note: declared here
 bool dcurl_init(dcurl_config *config);
      ^~~~~~~~~~
Makefile:176: recipe for target 'build/compat_ccurl.o' failed
make: *** [build/compat_ccurl.o] Error 1

**Comment by tylerw1369** [comment]
Looks like it's only when asking for BUILD_COMPAT=1 does it throw the error.

**Comment by marktwtn** [comment]
@tylerw1369 it is caused by the API change in version 0.6.0.
The `dcurl_init()` has a input parameter now.

I will make a fix today.
Sorry for the problem.
