### ISSUE TITLE
Unrecognized command line option error on RaspberryPi

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/dcurl#40]
RaspberryPi 3 model B

**Reproduce:**
`$ make check`
`
CC	build/curl.o
cc: error: unrecognized command line option ‘-msse2’
Makefile:103: recipe for target 'build/curl.o' failed
make: *** [build/curl.o] Error 1
`

**Comment by furuame** [comment]
ARM SIMD instruction set is not supported yet, I will port naive implementation into dcurl first.

NEON instruction set will be supported in the future.

**Comment by jserv** [comment]
Duplicated for #39

**Comment by furuame** [comment]
I will solve this issue by importing naive implementation by default if target machine not support SSE.

**Comment by furuame** [comment]
Issue solved by importing C implementation.

Environment:
```
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
```

Output:
```
pi@raspberrypi:~/dcurl $ make check
  CC    build/dcurl.o
  CC    build/pow_c.o
  CC    build/test-trinary.o
  LD    build/test-trinary
*** Validating build/test-trinary ***
        [ Verified ]
  CC    build/test-curl.o
  LD    build/test-curl
*** Validating build/test-curl ***
        [ Verified ]
  CC    build/test-pow_c.o
  LD    build/test-pow_c
*** Validating build/test-pow_c ***
        [ Verified ]
  LD    build/libdcurl.so
*** Validating build/test-multi_pow_cpu ***
        [ Verified ]
```
