### ISSUE TITLE
Invalid character on making check

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/dcurl#41]
Environment:
`$ uname -a
Linux Orz 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Reproduce:
`$ make check
  CC	build/curl.o
  CC	build/constants.o
  CC	build/trinary.o
  CC	build/dcurl.o
src/dcurl.c: In function ‘dcurl_entry’:
src/dcurl.c:115:16: warning: unused variable ‘num_gpu_thread’ [-Wunused-variable]
     static int num_gpu_thread = 0;
                ^
  CC	build/pow_sse.o
  CC	build/test-trinary.o
  LD	build/test-trinary
*** Validating build/test-trinary ***
	[ Verified ]
  CC	build/test-curl.o
  LD	build/test-curl
*** Validating build/test-curl ***
	[ Verified ]
  LD	build/libdcurl.so
*** Validating build/test-multi_pow_cpu ***
Unhandled exception in thread started by <function call_dcurl at 0x7fd7ccf137b8>
Traceback (most recent call last):
  File "./build/test-multi_pow_cpu", line 47, in call_dcurl
    trytes = TryteString(ret)
  File "/home/yillkid/.local/lib/python3.5/site-packages/iota/types.py", line 229, in __init__
    'trytes': trytes,
ValueError: Invalid character 'ÿ' at position 2673 (expected A-Z or 9).
Unhandled exception in thread started by <function call_dcurl at 0x7fd7ccf137b8>
Traceback (most recent call last):
  File "./build/test-multi_pow_cpu", line 47, in call_dcurl
    trytes = TryteString(ret)
  File "/home/yillkid/.local/lib/python3.5/site-packages/iota/types.py", line 229, in __init__
    'trytes': trytes,
ValueError: Invalid character '\x01' at position 2673 (expected A-Z or 9).
Unhandled exception in thread started by <function call_dcurl at 0x7fd7ccf137b8>
Traceback (most recent call last):
  File "./build/test-multi_pow_cpu", line 47, in call_dcurl
    trytes = TryteString(ret)
  File "/home/yillkid/.local/lib/python3.5/site-packages/iota/types.py", line 229, in __init__
    'trytes': trytes,
ValueError: Invalid character '\x01' at position 2673 (expected A-Z or 9).
Unhandled exception in thread started by <function call_dcurl at 0x7fd7ccf137b8>
Traceback (most recent call last):
  File "./build/test-multi_pow_cpu", line 47, in call_dcurl
    trytes = TryteString(ret)
  File "/home/yillkid/.local/lib/python3.5/site-packages/iota/types.py", line 229, in __init__
    'trytes': trytes,
ValueError: Invalid character 'ÿ' at position 2673 (expected A-Z or 9).
`

**Comment by furuame** [comment]
@yillkid Could you try this again?

**Comment by yillkid** [comment]
the other error:
`$ make check V=1
  CC	build/curl.o
  CC	build/constants.o
  CC	build/trinary.o
  CC	build/dcurl.o
src/dcurl.c: In function ‘dcurl_entry’:
src/dcurl.c:115:16: warning: unused variable ‘num_gpu_thread’ [-Wunused-variable]
     static int num_gpu_thread = 0;
                ^
  CC	build/pow_sse.o
  CC	build/test-trinary.o
  LD	build/test-trinary
*** Validating build/test-trinary ***
	[ Verified ]
  CC	build/test-curl.o
  LD	build/test-curl
*** Validating build/test-curl ***
	[ Verified ]
  LD	build/libdcurl.so
*** Validating build/test-multi_pow_cpu ***
mk/common.mk:27: recipe for target 'build/test-multi_pow_cpu.done' failed
make: *** [build/test-multi_pow_cpu.done] Error 1
rm build/test-trinary.o build/test-curl.o`

**Comment by furuame** [comment]
@yillkid Original issue has been solved. Please re-issue if there is a new error, Thanks!
