### ISSUE TITLE
Allow GPU from ccurl interface

### ISSUE THREAD

**Issue by gagathos** [DLTcollab/dcurl#42]
I'm trying to get gpu acceleration working for the ccurl interface.  It is currently hardcoded to only use CPU in src/compat-ccurl.c

I tried changing 

```
dcurl_init(1, 0);
```
to 
```
dcurl_init(1, 1);
```

But it results in a segmentation fault.  The pow_cl test works fine and I see it executing in nvidia monitor.

**Comment by gagathos** [comment]
Note that I get

```
*** Validating build/test-multi_pow_gpu ***
	[ Verified ]
```

But I don't see any activity from nvidia monitor for that test.

**Comment by furuame** [comment]
Thanks for your report! I will review it in these days.

**Comment by furuame** [comment]
`build/test-multi_pow_gpu` use gpu indeed, you can print something in switch case of `src/dcurl.c` to observe it, which is following:

```
*** Validating build/test-multi_pow_gpu ***
CPU do it!
GPU do it!
CPU do it!
GPU do it!
CPU do it!
GPU do it!
CPU do it!
CPU do it!
CPU do it!
GPU do it!
        [ Verified ]
```

About ccurl segmentation fault I have just reproduced it, I will deal with it soon. Thanks for your report again!

**Comment by furuame** [comment]
@gagathos Could you try again by using code in branch `fix-cl-bug`?

Thanks a lot!

**Comment by gagathos** [comment]
@chenwei-tw  Great fix! The segmentation fault is gone and I am able to get two threads going (though CPU seems to be faster than GPU on the machine I'm using)

I am now running into what looks like a race condition when handling two concurrent requests. It doesn't happen every time but eventually if I run a large enough benchmark it occurs, which leads me to believe it is a race condition linked to certain operations happening at the same time for both the CPU and GPU threads.  

Running the same code on the old dcurl (with only one CPU thread in the compat_ccurl) does not encounter the same issue, so I am guessing it is some issue handling multiple threads at the same time from the same application (this might just be a limitation of the ccurl interface design)

My code (using ccurl.interface.js) returns this, which looks like it is getting an empty output from the library. I am sorry I don't know how to debug it further.

```
/home/paperspace/iota-remote-pow-dcurl/node_modules/iota.lib.js/lib/crypto/converter/converter.js:87
            trits[i * 3] = trytesTrits[index][0];
                                             ^

TypeError: Cannot read property '0' of undefined
    at Object.trits (/home/paperspace/iota-remote-pow-dcurl/node_modules/iota.lib.js/lib/crypto/converter/converter.js:87:46)
    at Object.transactionObject (/home/paperspace/iota-remote-pow-dcurl/node_modules/iota.lib.js/lib/utils/utils.js:191:38)
    at /home/paperspace/iota-remote-pow-dcurl/node_modules/ccurl.interface.js/index.js:178:47
    at /home/paperspace/iota-remote-pow-dcurl/node_modules/ffi/lib/_foreign_function.js:115:9
```

**Comment by furuame** [comment]
Thanks for your testing 👍  I will deal with it in these days.

**Comment by furuame** [comment]
@gagathos Hi, may I ask how big the workload do you test? I cannot reproduce it :(

I create 1000 threads concurrently to call `ccurl_pow` and it works fine, while I use `tests/test-ccurl-multi_pow_gpu.py` in the branch `fix-cl-bug` to test.

**Comment by gagathos** [comment]
This is the js code that the ccurl interface uses.  Maybe it is an issue with the interface-- BUT as I said I am unable to reproduce the same issue with the single-threaded version of dcurl.  I will try to split the JS into multiple instances and see if it still occurs. I strongly suspect it's just the ccurl.interface.js doesn't handle multithreading very well. I will get back to you.

```
  // cCurl updates the nonce as well as the transaction hash
            libccurl.ccurl_pow.async(newTrytes, minWeightMagnitude, function(error, returnedTrytes) {

                if (error) {
                    return bundleCallback(error);
                }

                const newTxObject= iota.utils.transactionObject(returnedTrytes);

                // Assign the previousTxHash to this tx
                const txHash = newTxObject.hash;
                previousTxHash = txHash;

                finalBundleTrytes.push(returnedTrytes);

                return bundleCallback(null);
});
```

**Comment by gagathos** [comment]
Okay @chenwei-tw, I have tried 100 different ways to try to isolate the issue, but in every case that the GPU was being used it eventually resulted in the error. (not right away, though-- it was successfully doing POW using GPU and I saw it in the GPU monitor) If you'd like to add some sort of logging to this branch, I can run it and provide the log.

Here's how to replicate my test if you want to do it yourself (you will need nodejs and npm):

(On a machine with OpenCL/GPU)

- Clone https://github.com/gagathos/iota-gpu-pow and run `npm install` in the directory
- Replace libccurl.so with the dcurl from this branch (but name it libccurl.so)
- Optionally, edit remotePOW.js to change the port on the last line if you don't want it on port 80

Then in another folder,

- Clone https://github.com/gagathos/iota-pow-benchmark and run `npm install` in the directory
- Run the benchmark

```
node benchmark.js --iri-host=https://field.carriota.com --iri-port=443 -h http://localhost -p 80 -d 5 -M 5 -c 5 -b
```

(note that you can change the port in `-p 80` if you made it a different port, same with `-h`

**Comment by furuame** [comment]
@gagathos Very thankful for description of your program! I really need this to test reliability of dcurl.

If I have any progress, I will let you know.

**Comment by gagathos** [comment]
Also should make ccurl_compat GPU thread dependent on the GPU compile flag (it shouldn't try to make a GPU thread if we are not trying to make a GPU dcurl)

**Comment by furuame** [comment]
Hi @gagathos , I got this output from benchmark while pow server using `iotaledger/ccurl`. Is that normal?

```
Error: Request Error: Invalid transaction hash
    at Object.requestError (/home/ubuntu/cwei/iota-pow-benchmark/node_modules/iota.lib.js/lib/errors/requestErrors.js:11:12)
    at makeRequest.prepareResult (/home/ubuntu/cwei/iota-pow-benchmark/node_modules/iota.lib.js/lib/utils/makeRequest.js:298:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/ubuntu/cwei/iota-pow-benchmark/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/ubuntu/cwei/iota-pow-benchmark/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/ubuntu/cwei/iota-pow-benchmark/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/ubuntu/cwei/iota-pow-benchmark/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by gagathos** [comment]
No it is not! Are you using the libccurl that is compiled on your machine? The one in my repo probably won't work (but you can try)

I will test a fresh copy with ccurl and make sure all that code still works.

**Comment by gagathos** [comment]
I got it working from unchanged git clones. Here are the commands I think will get you there

```
mkdir testing
1672  cd testing
git clone https://github.com/gagathos/iota-gpu-pow.git
 1674  cd iota-gpu-pow
 1675  npm install
 1676  ls
 1677  cd ..
 1680  git clone https://github.com/iotaledger/ccurl.git
 1682  cd ccurl
 1683  mkdir build
 1694  git submodule update --init --recursive
 1695  cd build
 1696  cmake ..
 1699  cmake --build ..
 1701  cd ..
 1706  cd lib
 1708  cp libccurl.so ../../iota-gpu-pow/
 1712  cd iota-gpu-pow/
 1714  node remotePOW.js -p 8080
```

And here is the test that I ran:
```
node benchmark.js --iri-host=https://field.carriota.com --iri-port=443 -h http://[my server] -p 8080 -d 60 -M 1 -c 1 -b
```

Output of the remotePOW.js thread should look like this when test is running (if you have OpenCL)

```
node remotePOW.js -p 8080
Getting platforms... 

OpenCL Hashing with 32 loops...
OpenCL Hashing with 32 loops...
OpenCL Hashing with 32 loops...
OpenCL Hashing with 32 loops...
```
I don't know if this matters but I am using node v8.9.4

**Comment by furuame** [comment]
@gagathos Yo! Can you try the latest commit of branch `fix-cl-bug` again?

**Comment by gagathos** [comment]
I think that did the trick!

dcurl performance on my server

```
depth         200                               
concurrency   10                                
maxBundleSize 2                                 
publicTxns    no                                
minTime       4123.802861005068                 
maxTime       29706.699216008186                
totalTxns     600                               
totalTime     6152471.30213809                  
errors        0                                 
medianTime    27245.17774900794                 
avgTime       10254.118836896816 
```
And with ccurl
```
depth         200                               
concurrency   10                                
maxBundleSize 2                                 
publicTxns    no                                
minTime       5656.765320003033                 
maxTime       47790.1594029963                  
totalTxns     597                               
totalTime     15317535.01472801                 
errors        3                                 
medianTime    25099.824860990047                
avgTime       25657.512587484103  
```

**Comment by furuame** [comment]
@gagathos That sounds great and thanks again for your bug report
