### ISSUE TITLE
Show the hash rate of each implementation

### ISSUE THREAD

**Issue by furuame** [DLTcollab/dcurl#47]
Show the hash rate of each implementation by using `BUILD_BENCH` option

**Comment by furuame** [comment]
@marktwtn Please reference the implementation in [iotaledger/giota](https://github.com/iotaledger/giota)

**Comment by marktwtn** [comment]
The current implementation of getting the hash times would be calling an API
`getHashTimes(ImplContext *impl_ctx, void *pow_ctx)`

It would call the corresponding hardware-related function.
Take **CPU - SSE** as an example:
```
static uint64_t PoWSSE_getHashTimes(void *pow_ctx)
{
    uint64_t count = 0;
    PoW_SSE_Context *ctx = (PoW_SSE_Context *) pow_ctx;
    Pwork_struct *pitem = ctx->pitem;

    for (int i = 0; i < ctx->num_threads; i++) {
        if (pitem[i].ret >= 0 )
            count += (uint64_t)pitem[i].ret;
        else
            count += (uint64_t)(-(pitem[i].ret) + 1);
    }

    return count;
}
```

The **GPU** implementation is still under investigation.
The **FPGA** implementation would be completed by @ajblane .

**Comment by furuame** [comment]
@marktwtn About hash times of the OpenCL, you can take a look from giota. It seems trivial.

https://github.com/iotaledger/giota/blob/e34a409290248e6ff2205b06062d702690910f04/pow_cl.go#L94

**Comment by marktwtn** [comment]
`hash rate = hash count / PoW execution time`

There are two ways to get the `PoW execution time`.

1. Subtract the time before and after the `doThePoW` function.
2. Create an API like `getHashCount` to get the `PoW execution time`.
The time would be slightly accurate since the time subtraction would be done in the `doThePoW` function.
It excludes the function call, the PoW initialization part and other things. It focuses on the PoW execution time.

However, if the time unit is second, I think the `PoW execution time` may have no difference at all.

I prefer the method 2.
Is there any suggestion?

And I am thinking that the `hash rate` should be got with the API, too.

**Comment by furuame** [comment]
Method 2 might be better to get the time.

But I'm not sure do we really need "three" APIs to achieve the goal of this enhancement?

**Comment by marktwtn** [comment]
> But I'm not sure do we really need "three" APIs to achieve the goal of this issue?

How about

1. Create the `getHashRate` API and remove the others.

or

2. Create an API like `getPoWContext` which returns the pointer of PoW-related information. A structure contains `hash count` and `PoW execution time`.

**Comment by furuame** [comment]
>     2. Create an API like `getPoWContext` which returns the pointer of PoW-related information. A structure contains `hash count` and `PoW execution time`.

Let's do this! Create an API `getPoWInfo` to record the time and hashcount.

**Comment by marktwtn** [comment]
Here are the modifications I am going to do:

The return pointer of `getPoWInfo` function should be type cast to get the `hash count` and `PoW execution time` value.

I assume the `PoW information` structure of each implementation is the same.
Then I would like to extract it to the header file named `common.h`.
The concept is the same as the `common.h` header file in `tests` directory.

**Comment by chenwei-tw** [comment]
It's no need to return a pointer to a struct. Just return the value of the struct.

**Comment by furuame** [comment]
> The return pointer of `getPoWInfo` function should be type cast to get the `hash count` and `PoW execution time` value.

It's no need to return a pointer to a struct. Just return the value of the struct.

> I assume the `PoW information` structure of each implementation is the same.
> Then I would like to extract it to the header file named `common.h`.
> The concept is the same as the `common.h` header file in `tests` directory.

Good idea. After merging this PR, I will refactor the code to follow the OOP style.

**Comment by marktwtn** [comment]
This is what I am going to do.

1. Get the hash rate `n` times -> [ h`1`, h`2`, ......, h`n` ]

2. Calculate the `standard deviation` -> sqrt{ [ (h`1` - avg)^2 + ... + (h`n` - avg)^2 ] / n }

3. Show the result:
```
average hash rate: XXX kH/sec
with 95% confidence interval and error value (2 * standard deviation).
```

4. Show the hash rate with histogram.

---

@jserv is this what you expect to see?

**Comment by furuame** [comment]
> This is what I am going to do.
> 
>     1. Get the hash rate `n` times -> [ h`1`, h`2`, ......, h`n` ]
> 
>     2. Calculate the `standard deviation` -> sqrt{ [ (h`1` - avg)^2 + ... + (h`n` - avg)^2 ] / n }
> 
>     3. Show the result:
> 
> 
> ```
> average hash rate: XXX kH/sec
> with 95% confidence interval and error value (2 * standard deviation).
> ```
> 
>     4. Show the hash rate with histogram.

The original goal of this issue is achieved.

Let's create another issue for these features.

Thanks for @marktwtn and @ajblane's contribution. Close.
