### ISSUE TITLE
Fine-grained memory operation with dcurl_entry

### ISSUE THREAD

**Issue by ajblane** [DLTcollab/dcurl#56]
For example of using dcurl API, 
```
int8_t  *ret_trytes = null;
ret_trytes = dcurl_entry(...);
dcurl_destroy();
```
The ret_trytes is required to manually use free(), for example: 
```
int8_t  *ret_trytes = null;
ret_trytes = dcurl_entry(...);
dcurl_destroy();
free(ret_trytes);
```
I suggest the dcurl_destroy() API can be added a argument to release ret_trytes, for example:
```
int8_t  *ret_trytes = null;
ret_trytes = dcurl_entry(...);
dcurl_destroy(ret_trytes);
```
This is because the  sematic of dcurl_destroy is destroying usage resources. For using dcurl API, a developer maybe imagine ret_trytes can be released without using free() after using dcurl_destroy(). Would this suggestion is better?

**Comment by jserv** [comment]
The call sequence should be `dcurl_init` -> `dcurl_entry` -> `dcurl_destroy` where `dcurl_init` and `dcurl_destroy` are of the pair. I would suggest to add new function named `dcurl_release` which releases the resources allocated by `dcurl_entry`.

**Comment by furuame** [comment]
It seems that `dcurl_release` do the same thing as `free`, but more readable.
If `ret_trytes` passed as an argument, we can avoid this problem and the length of return tryte is known at static time.
```
int8_t ret_trytes[RETURN_TRYTES_LENGTH];
dcurl_entry(ret_trytes, ...);
```

**Comment by jserv** [comment]
Related: #20 
Cc. @chenwei-tw

**Comment by chenwei-tw** [comment]
@jserv Is #4 the correct issue you want to mention?

**Comment by ajblane** [comment]
The PR #59 achieves the goal. Close.
