### ISSUE TITLE
Facilitate thread pool to eliminate overhead while creating threads frequently

### ISSUE THREAD

**Issue by furuame** [DLTcollab/dcurl#58]
Since every CPU implementations, such as SSE and AVX, create many threads to find the nonce every time, the overhead cannot be ignored. [`libtuv`](https://github.com/Samsung/libtuv/blob/master/src/threadpool.c) offers a lightweight threadpool implementation for the embedded system.

This feature is expected to be implemented after the issue #57 is achieved. When the new interface is applied in `ducrl`, the threadpool can be hidden in the CPU PoW Algorithm context.

**Comment by marktwtn** [comment]
IOTA IRI has added the new [commit](https://github.com/iotaledger/iri/commit/51ebe60a3a80da9885bd1653e4c8f47c550df798) for the `--pow-threads` command option.

This affects the number of threads to use for proof-of-work calculation.
The thread pool would be affected, too.

**Comment by jserv** [comment]
> IOTA IRI has added the new [commit](https://github.com/iotaledger/iri/commit/51ebe60a3a80da9885bd1653e4c8f47c550df798) for the `--pow-threads` command option.
> This affects the number of threads to use for proof-of-work calculation.
> The thread pool would be affected, too.

Resolved in #87

**Comment by marktwtn** [comment]
I reference the branch `integrate-libtuv-threadpool` create by @2henwei.

The current `libtuv` would be compiled to static library(.a) without flag `fPIC`, which can not be used to generate the `libdcurl.so` file.
We have to modify `libtuv` and add the flag to generate another type of the library.

**Comment by marktwtn** [comment]
The rough time comparison of creating/using threads from `libtuv` or not in `dcurl`:

without threadpool (unit: second)
```
time: 0.000371
time: 0.000216
time: 0.000256
time: 0.000223
time: 0.000246
time: 0.000232
time: 0.000228
time: 0.000229
time: 0.000222
time: 0.000221
```

with threadpool  (unit: second)
```
time: 0.000411
time: 0.000015
time: 0.000033
time: 0.000016
time: 0.000028              
time: 0.000013
time: 0.000078
time: 0.000013
time: 0.000034
time: 0.000018
```

It is the first 10 result of running `PoW` 100 times.

---

However, it needs to do some modification in `libtuv` to integrate with `dcurl`.
I will open a pull request to `libtuv`.
After it is accepted, I will send the pull request to `dcurl`.

If it is not accepted, we might need to figure out other ways for integration.

**Comment by furuame** [comment]
> The rough time comparison of creating/using threads from `libtuv` or not in `dcurl`:
> 
> without threadpool (unit: second)
> 
> ```
> time: 0.000371
> time: 0.000216
> time: 0.000256
> time: 0.000223
> time: 0.000246
> time: 0.000232
> time: 0.000228
> time: 0.000229
> time: 0.000222
> time: 0.000221
> ```
> with threadpool (unit: second)
> 
> ```
> time: 0.000411
> time: 0.000015
> time: 0.000033
> time: 0.000016
> time: 0.000028              
> time: 0.000013
> time: 0.000078
> time: 0.000013
> time: 0.000034
> time: 0.000018
> ```
> It is the first 10 result of running `PoW` 100 times.

Wow! It seems there is an obvious improvement with `libtuv`

> 
> However, it needs to do some modification in `libtuv` to integrate with `dcurl`.

If you refer to the compiler-related flag modification, I have sent a similar issue to them.
https://github.com/pando-project/libtuv/pull/128

You can re-opened it.

> I will open a pull request to `libtuv`.
> After it is accepted, I will send the pull request to `dcurl`.
> 
> If it is not accepted, we might need to figure out other ways for integration.

**Comment by jserv** [comment]
> However, it needs to do some modification in `libtuv` to integrate with `dcurl`.
> I will open a pull request to `libtuv`.
> After it is accepted, I will send the pull request to `dcurl`.

As @2henwei suggested, we can reopen existing `libtuv` issue. Meanwhile, we can defer to our fork which includes the necessary build fixes as another Git submodule.

**Comment by jserv** [comment]
> The rough time comparison of creating/using threads from `libtuv` or not in `dcurl`:
> without threadpool (unit: second)
> ```
> time: 0.000371
> time: 0.000216
> time: 0.000256
> ```
> with threadpool (unit: second)
> ```
> time: 0.000411
> time: 0.000015
> time: 0.000033
> ```

We shall eliminate the impact of cache miss and page fault.
