### ISSUE TITLE
Support Pocl for CPU-only OpenCL implementation

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#69]
Current GPU-accelerated PoW is implemented via OpenCL, and Travis-CI in general doesn't have GPUs. The good thing about OpenCL is that you can use a CPU implementation of OpenCL, such as [Pocl](http://portablecl.org/), which uses Clang as an OpenCL C frontend and LLVM for kernel compiler implementation, and as a portability layer.

Pocl packages are available in recent Debian/Ubuntu repositories:
```
sudo apt install libpocl-dev
```

Utilities such as `clinfo` can find the new pocl ICD via
```
/etc/OpenCL/vendors/pocl.icd
```

**Comment by jserv** [comment]
Sample usage on Pocl and Travis: https://github.com/boostorg/compute/blob/master/.travis.yml

**Comment by jserv** [comment]
PoW linking to Pocl was not functioned as expected:
```
[dcurl] Implementation GPU (OpenCL) is initialized successfully
test-pow: tests/test-pow.c:111: main: Assertion `pow_ctx' failed.
Aborted (core dumped)
```

Reported by `clinfo`:
```
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 2.0 pocl 0.13, LLVM 3.8.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   Portable Computing Language
```

**Comment by furuame** [comment]
The reason might be that I only configure GPU devices on the dcurl.

https://github.com/DLTcollab/dcurl/blob/5dc64798263ffb223e33565f44ba83860692e607/src/clcontext.c#L171

**Comment by furuame** [comment]
@jserv  Should we create a now BUILD option in Makefile for CI test?

E.g.
```
#if defined(BUILD_CI)
    clGetDeviceIDs(platform[i], CL_DEVICE_TYPE_CPU, 0, NULL, &num_devices);
#else
    clGetDeviceIDs(platform[i], CL_DEVICE_TYPE_GPU, 0, NULL, &num_devices);
#endif
```

**Comment by jserv** [comment]
> @jserv Should we create a now BUILD option in Makefile for CI test?

Never write code dedicated to CI. We can provide some shotcuts or helper functions instead.

**Comment by furuame** [comment]
Maybe we should reserve the flexibility to let the user can configure their own OpenCL implementation. And we can provide some pre-tested config file like GPU or Pocl.

**Comment by jserv** [comment]
I agree with the way to improve the flexibility of adopting various OpenCL implementations like Pocl.

**Comment by marktwtn** [comment]
Since the current CI system is `buildkite` running on our own machine, we do not worry about the GPU problem.
Shall we close this issue or leave it as a future enhancement?

**Comment by jserv** [comment]
Close the historical issue
