### ISSUE TITLE
Acquire reliable hash rate distribution with the method of Statistics

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/dcurl#77]
The hash rate would be different at each time we execute PoW with the same hardware.
There might be a lot of factors which influence the hash rate value.

We try to measure the hash rate distribution and remove the extremely large and small hash rate.
A reliable range of hash rate value should be got with the method of Statistics.

**Comment by marktwtn** [comment]
This is what I am going to do.

1. Get the hash rate `n` times -> [ h`1`, h`2`, ......, h`n` ]

2. Calculate the `standard deviation` -> sqrt{ [ (h`1` - avg)^2 + ... + (h`n` - avg)^2 ] / n }

3. Show the result:
```
average hash rate: XXX kH/sec
with 95% confidence interval and error value (2 * standard deviation).
```

4. Show the hash rate with histogram.

**Comment by furuame** [comment]
I agree that time to find the nonce value is probability problem, but not the hash rate, which is dependent on the implementation.

**Comment by marktwtn** [comment]
> I agree that time to find the nonce value is probability problem, but not the hash rate, which is dependent on the implementation.

You are right.
I rewrite the title and the description of this issue.
