### ISSUE TITLE
de10 nano and it hangs on insmod cpowdrv.ko

### ISSUE THREAD

**Issue by tylerw1369** [DLTcollab/dcurl#78]
I have a de10 nano and have all the files loaded from the image and the new soc_system.rbf and it hangs when i try to load the cpowdrv.ko. It hangs when i try to load it via sh init_curl_pow.sh. i can load the other file curldrv.ko just fine.  im trying to get your dcurl to use the fpga but it also says *** no targets. stop. when i try to make anything.

**Comment by ajblane** [comment]
Do you download the soc_system.rbf from [rbf file for 33.7 Mhash/sec design]( https://github.com/LampaLab/iota_fpga/releases/tag/v0.3) that is supported by Lampa Lab for Intel DE10-nano board? Our team supports the soc_system.rbf only for Arrow SoCKit board.

**Comment by tylerw1369** [comment]
I got it to load and start to compile dcurl but doesnt finish. It gets to a point then says it cant find the file cpow-ctrl open fail: no such file or directory.
test-dcurl : tests/test-dcurl.c:53:main: assertion 'ret_trytes' failed . aborted
mk/common.mk27: recipe for target 'build/test-dcurl.done' failed 
make *** [build/test-dcurl.done] error 134

**Comment by tylerw1369** [comment]
I got everthing to build and load. When it gets to the point of testing the build it says implementation cpu is initialized correctly, then hangs there.  it doesnt do anything else or give me an error.

**Comment by tylerw1369** [comment]
![image](https://user-images.githubusercontent.com/39392335/51205112-604ea680-18c2-11e9-84e4-fd8d5e6133b5.png)

**Comment by ajblane** [comment]
It seems to be workable. On Arrow SoCKit board, execution time of pure C PoW implementation is about 43.000 sec. Perhaps, you can wait a minute for pure C PoW result.

By the way, you can verify the FPGA PoW implementation without dcurl as follows:
![image](https://user-images.githubusercontent.com/5338746/51219251-f0e0c180-196a-11e9-876f-cae21f20d95d.png)
Reference: https://www.youtube.com/watch?v=JJRlwTJHBCg&feature=youtu.be

**Comment by tylerw1369** [comment]
Ya it all works.  Looks like it ran 100 pow tests and that is what took it so long. Thanks for the help
