### ISSUE TITLE
Support the new command line option "--pow-threads" of IRI in dcurl

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/dcurl#86]
The IOTA `IRI` [commit](https://github.com/iotaledger/iri/commit/51ebe60a3a80da9885bd1653e4c8f47c550df798) has added the new command line option `--pow-threads` for assigning **Number of threads to use for proof-of-work calculation**.

The `dcurl` should support the `--pow-threads` in CPU implementation.

The priority of the CPU thread number would be:
1. Assigned by **IRI** `--pow-threads`
2. Environment variable `DCURL_NUM_CPU`
3. Core number detected by **dcurl**

**Comment by jserv** [comment]
I wonder the usability of env `$DCURL_NUM_CPU`. @chenwei-tw, can you comment this?
Once thread pool is fully integrated into dcurl, I don't think it is worthy to maintain such special mechanism.

**Comment by furuame** [comment]
The `pow-threads` can be used to initialize threadpool's number of threads instead `$DCURM_NUM_CPU`, but we need take care `ccurl-compat` scenario.

In the `ccurl-compat` interface, no system-related arguments can be passed to dcurl. If `DCURL_NUM_CPU` removed, `ccurl-compat` must use the default setting (e.g. CPU core number)

**Comment by marktwtn** [comment]
I guess the CPU thread number priority would be the same as I mentioned before.

Since `DCURL_NUM_CPU` and core number are detected during the `dcurl_init` function
and the `--pow-thread` value is passed when calling the `dcurl_entry` function,
there would be extra code inside the `dcurl_entry` for overwriting the initialized value.

**Comment by marktwtn** [comment]
I prefer remove the `DCURL_NUM_CPU` and let `ccurl-compat` use the default setting.
Since if `--pow-threads` is greater than `DCURL_NUM_CPU`, the memory allocation in the `PoWXXX_Context_Initialize` function would not be enough.

@chenwei-tw is it acceptable in `ccurl-compat`? I am not really familiar with it.

**Comment by furuame** [comment]
> I guess the CPU thread number priority would be the same as I mentioned before.
> Since DCURL_NUM_CPU and core number are detected during the dcurl_init function
and the --pow-thread value is passed when calling the dcurl_entry function,
there would be extra code inside the dcurl_entry for overwriting the initialized value.

Ok I got it. That's alright if the `dcurl_entry` would be passed with `--pow-thread`

> I prefer remove the DCURL_NUM_CPU and let ccurl-compat use the default setting.
Since if --pow-threads is greater than DCURL_NUM_CPU, the memory allocation in the PoWXXX_Context_Initialize function would not be enough.

It's okay. We can use the saturated value (`DCURL_NUM_CPU`) if `--pow-threads` is greater than this.
