### ISSUE TITLE
Optimize Trits/Trytes manipulation with SIMD techniques

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#92]
Current tris/trytes manipulation in file `src/trinary.c` is quite naive, and it proceeds only a byte at one time:
```c
static bool validateTrytes(Trobject_t *trytes) {
    ...
    for (int i = 0; i < trytes->len; i++)
        if ((trytes->data[i] < 'A' || trytes->data[i] > 'Z') &&
            trytes->data[i] != '9')
            return false;
    return true;
}
```

[strcmp(3)](https://linux.die.net/man/3/strcmp) and its variants are crucial part of nearly every software project ever made. A modern CPU can process 32bit-256bit at a time inside a core, if it does only 8 bit in each operation then large parts of the computing capacity are unused. If the string code processes a lot of data and slows down the program it’s better to find some way to use this unused computing capability.

We can operate on each block rather than one byte to speed up string comparison as [Speeding up string compare and sorting](http://mgronhol.github.io/fast-strcmp/) suggested:
```c
int fast_compare(const char *ptr0, const char *ptr1, int len) {
    int fast = len / sizeof(size_t) + 1;
    int offset = (fast - 1) * sizeof(size_t);
    int current_block = 0;
    if (len <= sizeof(size_t)) { fast = 0; }
    size_t *lptr0 = (size_t*) ptr0;
    size_t *lptr1 = (size_t *) ptr1;

    while (current_block < fast) {
        if ((lptr0[current_block] ^ lptr1[current_block])) {
            for (int pos = current_block * sizeof(size_t); pos < len ; ++pos) {
                if ((ptr0[pos] ^ ptr1[pos]) || (ptr0[pos] == 0) || (ptr1[pos] == 0))
                    return  (int)((unsigned char) ptr0[pos] - (unsigned char) ptr1[pos]);
            }
        }
        ++current_block;
    }

    while (len > offset) {
        if ((ptr0[offset] ^ ptr1[offset]))
            return (int)((unsigned char) ptr0[offset] - (unsigned char) ptr1[offset]); 
        ++offset;
    }	
    return 0;
}
```

On modern x86 CPUs an alternative is to use the SSE 4.2 string instructions PCMP*STR*. They are essentially programmable comparison engines to compare two 128bit vectors at a time. They can handle string end detection and various other cases directly. They are very powerful, but since they are so configurable also hard to use (2**9 possible combinations). The hardware can do all these operations in parallel, so it’s more efficient than a explicit loop.

With such optimization techniques, [Validating UTF-8 strings using as little as 0.7 cycles per byte](https://lemire.me/blog/2018/05/16/validating-utf-8-strings-using-as-little-as-0-7-cycles-per-byte/) claimed 10x speedup while validating UTF-8 strings. If we focus on tris/trytes conversion, the experience about [Accelerating UTF-8 Decoding Using SIMD Instructions](https://researcher.watson.ibm.com/researcher/files/jp-INOUEHRS/IPSJPRO2008_SIMDdecoding.pdf) is worthy adopting since it claims 15x speed up with 3-bytes character-only operations.

Reference:
* [A calculator for PCMPSTR](https://halobates.de/blog/p/207#comments)
* [Implementing strcmp, strlen, and strstr using SSE 4.2 instructions](https://www.strchr.com/strcmp_and_strlen_using_sse_4.2)
* [fastvalidate-utf-8](https://github.com/lemire/fastvalidate-utf-8)
* [SIMD UTF8 Validation in Rust](https://github.com/killercup/simd-utf8-check) (comprehensive report!)
* [Fast UTF-8 validation with range algorithm (NEON+SSE4)](https://github.com/cyb70289/utf8/)
* [Flexible and Economical UTF-8 Decoder](https://bjoern.hoehrmann.de/utf-8/decoder/dfa/)

**Comment by jserv** [comment]
Cc. @wusyong, in private qubic development discussion, there was a proposal to speed up trinary operations with SIMD as well. I was working on lookup table (LUT) oriented optimizations, but we can do it better with SSE4.2 intrinsics.

**Comment by marktwtn** [comment]
I started with adding a `SSE4.2` version of `validateTrytes` function.
The `SSE4.2` version compares 128-bit(16-byte) at one time.

By running the existing testcases in `dcurl`, I got the data and transferred it into the graph below.
![graph](https://user-images.githubusercontent.com/6748200/52717602-72fcee00-2fdc-11e9-91c0-f14cc431abe3.png)

Since we have different input size, the time without `SSE4.2` instructions varies a lot.
As a result, the `SSE4.2` version behaves pretty well.

I will continue to investigate the optimization of the functions `validateTrits`, `trytes_from_trits` and `trits_from_trytes`.

**Comment by jserv** [comment]
@paulhandy, FYI. we discussed SIMD-optimized trinary conversion about 1 year ago, and it is time to make it happen.

**Comment by marktwtn** [comment]
**Optimize `validateTrits` function:**

The `SSE4.2` instruction is useless here.
Instead, the optimized code is combined with `SSE2` and `SSE4.1` instructions.

- Original code:
```C
    for (int i = 0; i < trits->len; i++)
        if (trits->data[i] < -1 || trits->data[i] > 1)
            return false;
    return true;
```

- Optimized code:
The first loop compares 128-bit(16-byte) at one time, 
and the second loop handles the rest of the bytes which can not be 128-bit long. 
```C
    int block = sizeof(__m128i)/sizeof(int8_t);
    int high = 0xFFFFFFFF;
    int low = 0x01010101;  // the variable should be renamed
    __m128i one = _mm_set_epi32(low, low, low, low);
    __m128i neg_one = _mm_set_epi32(high, high, high, high);
    __m128i mask = _mm_set_epi32(high, high, high, high); // SSE2  0b111...111
    for (int i = 0; i < (trits->len) / block; i++) {
        // the for loop does not handle the character after null-teminated character
        __m128i data = _mm_loadu_si128((__m128i *)(trits->data) + i);
        __m128i result = _mm_or_si128(
                             _mm_cmplt_epi8(data, neg_one), // < -1
                             _mm_cmpgt_epi8(data, one)   // > 1
                         );
        if (!_mm_test_all_zeros(result, mask)) // this instruction is SSE4.1
            return false;
    }
    for (int i = ((trits->len) / block) * block; i < trits->len; i++) {
        if (trits->data[i] < -1 || trits->data[i] > 1)
            return false;
    }
    return true;
```

By running the existing testcases in `dcurl`, I got the data and transferred it into the graph below.
![graph](https://user-images.githubusercontent.com/6748200/52769953-d6366100-306c-11e9-9eea-3daf8f0f3645.png)

The optimized code seldom behaves worse when the input size is small.

**Comment by marktwtn** [comment]
**Optimize `trytes_from_trits` function:**

The intrinsic functions used are `SSE2` and the shuffle function of `SSSE3`.

The new optimized code is quite complicated, but it does improve performance a little.

Performance chart:
![graph](https://user-images.githubusercontent.com/6748200/53292704-87718f80-3801-11e9-830b-e1d7c174ad68.png)

We only have the input data size of 81 and 243 when calling the `trytes_from_trits` function, which are quite small.

**Comment by marktwtn** [comment]
I was wondering about the timing to activate the optimization, since the intrinsic instruction used by each function optimization is different.

For example:
`validateTrytes` - **SSE4.2**
`validateTrits` - **SSE4.1**
`trytes_from_trits` - **SSSE3**

Shall we make `dcurl` detect the instruction set of the hardware automatically and use the optimization if the instruction set is supported?

**Comment by jserv** [comment]
Only x86_64 architecture is considered. We can assume SSE4.2 is minimal requirement.

**Comment by marktwtn** [comment]
**Optimize `trytes_from_trits` function:**

The chart data is collected from the test cases of the `dcurl` with `BUILD_STAT` enabled.

Performance chart:
![graph](https://user-images.githubusercontent.com/6748200/55577251-b7d41400-5745-11e9-9eea-fe75ed3b3fc0.png)

    Without SIMD optimization:
    Input size(byte) - Average time(nsec)
    81               - 406.3
    243              - 444.6
    
    With SIMD optimization:
    Input size(byte) - Average time(nsec)
    81               - 261.5
    243              - 162.7

The chart shows that sometimes the SIMD version is slower, but the average value behaves better.
If the input size is larger, the performance improvement might be more evident.
However, we only have to deal with the input size 81 and 243.

**Comment by jserv** [comment]
> The chart shows that sometimes the SIMD version is slower, but the average value behaves better.
> If the input size is larger, the performance improvement might be more evident.
> However, we only have to deal with the input size 81 and 243.

Will SIMD shortcut benefit from prefetch and/or software pipelining technique?

**Comment by marktwtn** [comment]
In [entangled](https://github.com/iotaledger/entangled), there are several files for testing.
Some of them use the same function like `trytes_from_trits()`.

For example:
MAM troika related test (trit input size = 729): [test_trokia.c](https://github.com/iotaledger/entangled/blob/09f58f17072053798b0d4adec0b1263eb005641c/mam/troika/tests/test_troika.c)
crypto ISS related tests (trit input size = 6561 ): [test_iss_curl.c](https://github.com/iotaledger/entangled/blob/69442f6503b7f0fe74f0fabbe8ed55729128555d/common/crypto/iss/v1/tests/test_iss_curl.c) [test_iss_kerl.c](https://github.com/iotaledger/entangled/blob/69442f6503b7f0fe74f0fabbe8ed55729128555d/common/crypto/iss/v1/tests/test_iss_kerl.c)

**Comment by marktwtn** [comment]
I ran the test of [entangled](https://github.com/iotaledger/entangled) [test_iss_curl.c](https://github.com/iotaledger/entangled/blob/69442f6503b7f0fe74f0fabbe8ed55729128555d/common/crypto/iss/v1/tests/test_iss_curl.c) with trit input size = 6561.

Performance chart:
![graph](https://user-images.githubusercontent.com/6748200/56481015-5d7dd600-64ef-11e9-819e-1161d429ae83.png)

```
Without SIMD optimization:
Input size(byte) - Average time(nsec)
6561             - 53166.93

With SIMD optimization:
Input size(byte) - Average time(nsec)
6561             - 27290.99
```

Although the average value was affected by the extreme value, the performance chart shows that the optimization does increase speed.
Compare with the previous comment, the SIMD `trytes_from_trits()` function behaves better with larger input size.

**Comment by marktwtn** [comment]
**Optimize `trits_from_trytes` function:**

The chart data is collected from the test cases of the dcurl with `BUILD_STAT` and `BUILD_SSE` enabled.
It has two SIMD optimized data. One of them uses the intrinsic function of `SSE4.2`.
The optimization without `SSE4.2` is the previous written code.
It does not behave well in the last experiment, hence I decided to write a better version.
Then here comes the faster SIMD optimization with `SSE4.2`.

![graph](https://user-images.githubusercontent.com/6748200/57724035-804d7580-76bc-11e9-916b-44e5623b03bb.png)

```
Without SIMD optimization:
Input size(byte) - Average time(nsec)
81               - 355.6
2592             - 5752.3
2673             - 6273.0

With SIMD optimization:
Input size(byte) - Average time(nsec)
81               - 272.2
2592             - 3823.9
2673             - 4136.3

With SIMD + SSE4.2 optimization:
Input size(byte) - Average time(nsec)
81               - 167.1
2592             - 1751.8
2673             - 2098.8
```

As the input size becomes bigger, the performance becomes better.
