### ISSUE TITLE
Invalid memory operations on calling initialize/destroy functions repetitively

### ISSUE THREAD

**Issue by wusyong** [DLTcollab/dcurl#94]
There's a bug when utilizing dcurl after first time. Calling `dcurl_destroy` in second time would yield double free error:

```
[dcurl] Implementation CPU (Intel SSE) is initialized successfully
test-dcurl(34354,0x1115395c0) malloc: *** error for object 0x7f9ed4d00000: pointer being freed was not allocated
test-dcurl(34354,0x1115395c0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 34354 Abort trap: 6           ./build/test-dcurl
make: *** [build/test-dcurl.done] Error 134
```

Step to reproduce:
Put another `dcurl_init` and `dcurl_destroy` in `test_dcurl` test, then simply `make check`.

**Comment by jserv** [comment]
I rebuilt `dcurl` with [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer), and `make check` aborted with the following messages:
```
==52602==ERROR: LeakSanitizer: detected memory leaks
...
SUMMARY: AddressSanitizer: 37866102 byte(s) leaked in 663 allocation(s).
```

**Comment by marktwtn** [comment]
In `dcurl`, we maintain a double-linked list with nodes representing different hardware architectures.

`dcurl_init()` should add the nodes into the list and `dcurl_destroy()` should remove the nodes from the list.
However, the current implementation of `dcurl_destroy()` does not call the corresponding function to remove it.

As calling `dcurl_init()` and `dcurl_destroy()` repeatedly without removing the nodes, the list would behave unexpectedly.

In this issue, the unexpected behaviour makes `dcurl_destroy()` call the function `destroyImplContext()` more times than it should have, which causes the memory free error.
