### ISSUE TITLE
Optimized curl transform formulas

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#97]
`powsrv.io` team optimized the curl transform formulas, claiming 7% speedup. `dcurl` should benefit from the changes proposed in [entangled PR #803](https://github.com/iotaledger/entangled/pull/803).

Reference: [Curl improvement in IRI](https://github.com/iotaledger/iri/pull/1330).

**Comment by wusyong** [comment]
This uses Quine-McCluskey algo. to optimize transform function. While `BUILD_SSE` has significant improvement by **~10%**, `BUILD_AVX` only gets **~1%**. The benchmark is taken on node0 with [commit 4afc057](https://github.com/wusyong/dcurl/commit/4afc0577c4019197b39bed08c4d6529fb3fb6dca).

### SSE
`make check BUILD_STAT=1`:
* Original:
```
[dcurl] Implementation CPU (Intel SSE) is initialized successfully
PoW execution times: 100 times.
Hash rate average value: 7997.251 kH/sec,
with the range +- 109.604 kH/sec including 95% of the hash rate values.
```

* Optimized:
```
[dcurl] Implementation CPU (Intel SSE) is initialized successfully
PoW execution times: 100 times.
Hash rate average value: 9075.665 kH/sec,
with the range +- 112.197 kH/sec including 95% of the hash rate values.
```
### AVX
`make check BUILD_AVX=1 BUILD_STAT=1`:
* Original:
Hash rate are around 94XX kH/s with multiple tests
```
[dcurl] Implementation CPU (Intel AVX) is initialized successfully
PoW execution times: 100 times.
Hash rate average value: 9452.758 kH/sec,
with the range +- 394.444 kH/sec including 95% of the hash rate values.
```

* Optimized:
Hash rate are around 95XX kH/s with multiple tests
```
[dcurl] Implementation CPU (Intel AVX) is initialized successfully
PoW execution times: 100 times.
Hash rate average value: 9578.751 kH/sec,
with the range +- 341.911 kH/sec including 95% of the hash rate values.
```

**Comment by jserv** [comment]
@wusyong, Can you manually disable AVX2-specific execution paths and compare again?

**Comment by wusyong** [comment]
@jserv Results remain same. And after testing AVX2 on devorg the results have no change and sometimes worse. I even just removed [operator](https://github.com/wusyong/dcurl/blob/b10529cae2255727eb5c1f555b5e13a84a27fcbb/src/pow_avx.c#L36) for `ngamma` and `alpha` then it will be worse.

### AVX2
Original:
Hash rate is around 25xxx kH/sec
```
[dcurl] Implementation CPU (Intel AVX) is initialized successfully
PoW execution times: 100 times.
Hash rate average value: 25524.854 kH/sec,
with the range +- 6373.506 kH/sec including 95% of the hash rate values.
```

Optimized:
Hash rate is around 25xxx~24XXX kH/sec
```
[dcurl] Implementation CPU (Intel AVX) is initialized successfully
PoW execution times: 100 times.
Hash rate average value: 24271.330 kH/sec,
with the range +- 7454.857 kH/sec including 95% of the hash rate values.
```

**Comment by jserv** [comment]
Extra parameters `-march=native -mtune=native` might be set to `CFLAGS` if we would like to ask GCC to  operate normally without causing #GP(0) on any byte-granularity alignment (unlike SSE instructions).

IMHO, applying Quine-McCluskey algorithm for micro-optimization is reasonable, and we can rework AVX backend later. Please send pull request(s) along with appropriate explanation.

Reference: https://software.intel.com/sites/default/files/managed/b4/3a/319433-024.pdf

**Comment by muXxer** [comment]
You are welcome ;)
