### ISSUE TITLE
Ensure FPGA related repositories hosted in DLTcollab umbrella

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#98]
[Build instructions](https://github.com/DLTcollab/dcurl/blob/dev/docs/build-n-test.md) mentioned RBF file for Arrow SoCKit board. For the sake of consistency, we would like to host FPGA related repository under [DLTcollab](https://github.com/DLTcollab).

Expected output:
1. Host all FPGA related repositories in DLTcollab;
2. Adjust corresponding wording and information about FPGA;

**Comment by ajblane** [comment]
https://github.com/DLTcollab/iota_fpga/pull/1

**Comment by jserv** [comment]
Landed. Thank @ajblane again.
